[project]
name = "ALEX"
version = "0.1"
description = "Artificial Life EXperiment (a game for Unix console)"
authors = [
    {name = "Brandon Corfman", email = "bcorfman@fastmail.fm"},
]
dependencies = ["blessed"]
requires-python = ">=3.9"
license = {text = "MIT"}
[project.optional-dependencies]

[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true


[tool.pdm.dev-dependencies]
dev = [
    "coverage>=6.3.2",
    "coveralls>=3.3.1",
    "nuitka>=0.7.7",
    "pytest>=7.1.2",
    "pytest-asyncio>=0.18.3",
    "pysnooper>=1.1.1"]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
